from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np

try:
    from scipy.integrate import simpson
except Exception:  # pragma: no cover
    simpson = None


def load_transmission_csv(path: str | Path, energy_col: str = "E", transmission_col: str = "Gz") -> tuple[np.ndarray, np.ndarray]:
    """Load a two-column CSV generated by the transport scripts."""
    import pandas as pd

    frame = pd.read_csv(path)
    return frame[energy_col].to_numpy(dtype=float), frame[transmission_col].to_numpy(dtype=float)


def _fermi(energy: np.ndarray, mu: float, temperature: float) -> np.ndarray:
    if temperature <= 0:
        return (energy <= mu).astype(float)
    with np.errstate(over="ignore", under="ignore"):
        return 1.0 / (np.exp((energy - mu) / temperature) + 1.0)


def legacy_fermi_window(
    energy: np.ndarray,
    bias: float,
    mu_l_up: float,
    mu_r_up: float,
    temperature: float,
) -> np.ndarray:
    """
    Reproduce the window used by the original Colab scripts.

    The right-electrode convention is kept intentionally so the archive does not
    silently change published or in-progress numbers.
    """
    left = _fermi(energy, (mu_l_up / 2.0) + (bias / 2.0), temperature)
    if temperature <= 0:
        right = (energy <= -((mu_r_up / 2.0) + (bias / 2.0))).astype(float)
    else:
        with np.errstate(over="ignore", under="ignore"):
            right = 1.0 / (np.exp((energy + (mu_r_up / 2.0 + bias / 2.0)) / temperature) + 1.0)
    return left - right


def canonical_fermi_window(
    energy: np.ndarray,
    mu_left: float,
    mu_right: float,
    temperature: float,
) -> np.ndarray:
    """Standard Landauer window f_L(E) - f_R(E)."""
    return _fermi(energy, mu_left, temperature) - _fermi(energy, mu_right, temperature)


def integrate_current_curve(
    energy: np.ndarray,
    transmission: np.ndarray,
    window: np.ndarray,
) -> float:
    values = transmission * window
    if simpson is not None:
        return float(simpson(values, x=energy))
    return float(np.trapz(values, x=energy))


def _write_dat(path: Path, x_values: Iterable[float], y_values: Iterable[float]) -> None:
    rows = np.column_stack((np.asarray(list(x_values), dtype=float), np.asarray(list(y_values), dtype=float)))
    np.savetxt(path, rows, fmt="%.6e")


def _write_csv(path: Path, headers: list[str], rows: list[list[float]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(headers)
        writer.writerows(rows)


@dataclass
class CaseConfig:
    label: str
    pattern: str
    output_basename: str


def _resolve_pattern(pattern: str, config_dir: Path, n_value: int) -> Path:
    candidate = Path(pattern.format(N=n_value))
    if candidate.is_absolute():
        return candidate
    return (config_dir / candidate).resolve()


def run_from_config(config_path: str | Path) -> dict[str, object]:
    config_file = Path(config_path).resolve()
    config_dir = config_file.parent
    config = json.loads(config_file.read_text(encoding="utf-8"))

    lengths = list(config["lengths"])
    cases = [CaseConfig(**case) for case in config["cases"]]
    output_dir = (config_dir / config.get("output_dir", "../results/current")).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    use_legacy_window = bool(config.get("use_legacy_window", True))
    bias = float(config.get("bias", 4.0))
    temperature = float(config.get("temperature", 1e-9))
    mu_l_up = float(config.get("mu_l_up", 1.0))
    mu_r_up = float(config.get("mu_r_up", -1.0))

    table_headers = ["N"] + [case.label for case in cases]
    table_rows: list[list[float]] = []

    case_results: dict[str, list[float]] = {case.label: [] for case in cases}

    for n_value in lengths:
        row = [float(n_value)]
        for case in cases:
            curve_path = _resolve_pattern(case.pattern, config_dir, int(n_value))
            energy, transmission = load_transmission_csv(curve_path)
            if use_legacy_window:
                window = legacy_fermi_window(energy, bias=bias, mu_l_up=mu_l_up, mu_r_up=mu_r_up, temperature=temperature)
            else:
                window = canonical_fermi_window(
                    energy,
                    mu_left=(mu_l_up / 2.0) + (bias / 2.0),
                    mu_right=(mu_r_up / 2.0) - (bias / 2.0),
                    temperature=temperature,
                )
            current = integrate_current_curve(energy, transmission, window)
            case_results[case.label].append(current)
            row.append(current)
        table_rows.append(row)

    combined_csv = output_dir / f"{config.get('name', 'current_vs_length')}.csv"
    _write_csv(combined_csv, table_headers, table_rows)

    for case in cases:
        output_path = output_dir / f"{case.output_basename}.dat"
        _write_dat(output_path, lengths, case_results[case.label])

    return {
        "config": str(config_file),
        "output_dir": str(output_dir),
        "combined_csv": str(combined_csv),
        "cases": {case.label: str(output_dir / f"{case.output_basename}.dat") for case in cases},
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Integrate current-vs-length curves from transmission CSV files.")
    parser.add_argument("--config", required=True, help="Path to a JSON configuration file.")
    args = parser.parse_args(argv)
    result = run_from_config(args.config)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
