#!/usr/bin/env python3
"""
Symbolic audit for the two-site CISS effective Hamiltonian.

Checks:
1. Hermitian central Hamiltonian structure.
2. Schur-complement reduction of the exact 4x4 Green function.
3. Exact condition under which spin-conserving and spin-flip channels decouple.
4. Recovery of the usual decoupled-channel Green function in the TRS/Kramers limit.

Run:
    python ciss_symbolic_audit.py
"""

import sympy as sp

# Use real symbols where appropriate
V, a2 = sp.symbols("V a2", nonzero=True, real=True)
Du, Dd = sp.symbols("D_u D_d", complex=True)
Du_c, Dd_c = sp.symbols("D_u_conj D_d_conj", complex=True)

# Inter-site coupling block C in basis (site1 up/down) -> (site2 up/down)
# H = [[h1, C], [C^dagger, h2]]
C = sp.Matrix([[V, Du], [Dd, V]])
Cdag = sp.Matrix([[V, Dd_c], [Du_c, V]])  # explicit formal conjugates
CCdag = sp.simplify(C * Cdag)

print("=== Inter-site coupling block C ===")
sp.print_latex(C)
print(C)

print("\n=== C C^dagger ===")
print(CCdag)
print("LaTeX:")
sp.print_latex(CCdag)

print("\nOff-diagonal Schur/interference terms:")
off_ud = sp.simplify(CCdag[0, 1])
off_du = sp.simplify(CCdag[1, 0])
print("(C C†)_{up,down} =", off_ud)
print("(C C†)_{down,up} =", off_du)

# TRS/Kramers pair condition in this gauge: D_down = -D_up^*
# Therefore Dd_c = -Du and Dd = -Du_c.
subs_trs = {Dd_c: -Du, Dd: -Du_c}
CCdag_trs = sp.simplify(CCdag.subs(subs_trs))
print("\n=== C C^dagger under TRS condition D_down = -D_up^* ===")
print(CCdag_trs)
print("LaTeX:")
sp.print_latex(CCdag_trs)

print("\nConclusion:")
print("Under TRS, off-diagonal spin mixing generated by Schur decimation cancels exactly.")
print("When D_down != -D_up^*, this cancellation is lost and the full 4x4 Green function is required.")

# Define scalar a1,a2 and exact Schur complement in the simplified spin-degenerate case.
a1 = sp.symbols("a1", nonzero=True)
I2 = sp.eye(2)
A = a1 * I2
B_inv = (1/a2) * I2
Seff = sp.simplify(A - C * B_inv * Cdag)
Seff_trs = sp.simplify(Seff.subs(subs_trs))

print("\n=== Exact site-1 Schur denominator A - C B^{-1} C† ===")
print(Seff)
print("LaTeX:")
sp.print_latex(Seff)

print("\n=== Schur denominator under TRS ===")
print(Seff_trs)
print("LaTeX:")
sp.print_latex(Seff_trs)

print("\nIn the TRS limit, each diagonal element has the form")
print("    a1 - (V^2 + |D_up|^2)/a2")
print("which is the decoupled-channel expression used in the analytical limit.")
